language: node_js
node_js:
  - '6'

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - 'npm test'

after_script:
  - 'find ./coverage -name lcov.info -exec cat {} \; | ./node_modules/.bin/coveralls'
  - 'npm run build'
  - 'sha256sum ./dist/chrome/*'
  - 'sha256sum ./dist/firefox/*'
  - 'sha256sum ./dist/opera/*'
